pulp/pulpcore-plugin

- pulpcore/plugin/viewsets.py
[noissue]
Please be sure you have read our documentation regarding contributing
here:
https://docs.pulpproject.org/en/3.0/nightly/contributing/index.html
There you can read a Contribution Checklist and learn more about
appropriate branches and rebasing among other things.
Once you are ready to create a pull request:
documentation here:
https://docs.pulpproject.org/en/3.0/nightly/contributing/git.html#commit-message
your pull request into the notes/comments for the relevant bug in the
issue tracker and change the status to POST.
by your pull request.  You can see the status of these tests on the
page for your pull request.  If there are failures, please try to
fix them and update your pull request.
Thank you so much for contributing to Pulp!
> Fix noqa format

- .travis/install.sh
- .travis/script.sh
> Fixing pulpcore path

- .coveragerc
> Removing code coverage source setting

- .travis/install.sh
re: #4193
https://pulp.plan.io/issues/4193
> Changes the order in which packages are installed

- pulpcore/plugin/viewsets.py
> Expose RemoteFilter

- .travis.yml
> Setting the password for pypi

- .travis/before_script.sh
- .travis/script.sh
- .travis/server.yaml
https://pulp.plan.io/issues/3693
re #3693
> Fixes Travis from Lazy changes

- .travis.yml
> Adds list of stages with conditions.

- docs/release-notes/index.rst
- setup.py
[noissue]
Please be sure you have read our documentation regarding contributing
here:
https://docs.pulpproject.org/en/3.0/nightly/contributing/index.html
There you can read a Contribution Checklist and learn more about
appropriate branches and rebasing among other things.
Once you are ready to create a pull request:
documentation here:
https://docs.pulpproject.org/en/3.0/nightly/contributing/git.html#commit-message
your pull request into the notes/comments for the relevant bug in the
issue tracker and change the status to POST.
by your pull request.  You can see the status of these tests on the
page for your pull request.  If there are failures, please try to
fix them and update your pull request.
Thank you so much for contributing to Pulp!
> Updating release notes and version info for 0.1.0b16

- pulpcore/plugin/stages/association_stages.py
The pipeline concept is based on:
1. Identifying existing content units that represent content that should be
part of the new repo version (QueryExistingContentUnits stage)
2. Saving all other new content units (ContentUnitSaver stage)
In conclusion, all declarative_content.content instances _must_ be in the
database before they enter the (un)association stages.  All the heavy
lifting based on unit keys has already been done.
Thus, the (un)association stages should work on primary keys only.
This also enables to use pipelines which are "local" to the repo version,
i.e. pipelines that do not rely on global natural keys for content, but
only query and associate existing content in the base repository version.
[noissue]
> Make (un)association stages work on primary keys

- docs/plugin-writer/planning-guide.rst
> Adding database compatibility section

- pulpcore/plugin/stages/content_unit_stages.py
- pulpcore/plugin/stages/declarative_version.py
- pulpcore/plugin/stages/models.py
https://pulp.plan.io/issues/4294
re #4294
> Add futures to DeclarativeContent

- pulpcore/plugin/exceptions.py
- pulpcore/plugin/tasking.py
> Add exceptions to plugin api

- pulpcore/plugin/stages/artifact_stages.py
- pulpcore/plugin/stages/models.py
As discussed with @gmbnomis in https://github.com/pulp/pulpcore-plugin/pull/30#issuecomment-452919468 , the downloading process could get some cleanup. Here is my attempt.
> Refactor download process

- docs/plugin-writer/concepts/subclassing/serializers.rst
- docs/plugin-writer/plugin-walkthrough.rst
re: #4366
https://pulp.plan.io/issues/4366
> Update the plugin writer guide for serializer changes

- docs/api-reference/stages.rst
- pulpcore/plugin/stages/__init__.py
- pulpcore/plugin/stages/api.py
- pulpcore/plugin/stages/artifact_stages.py
- pulpcore/plugin/stages/association_stages.py
- pulpcore/plugin/stages/content_stages.py
- pulpcore/plugin/stages/declarative_version.py
- pulpcore/plugin/stages/profiler.py
- pulpcore/tests/unit/stages/test_artifactdownloader.py
- pulpcore/tests/unit/stages/test_stages.py
This is kind of a followup for #32.
Also it is meant as a preparation for https://pulp.plan.io/issues/4296
> Refactor stages

- docs/api-reference/stages.rst
- pulpcore/plugin/stages/content_stages.py
- pulpcore/plugin/stages/models.py
The code was added, but an example will make it more usable.
https://pulp.plan.io/issues/4294
closes #4294
> Adds example of "looping" content

- docs/release-notes/index.rst
> Fixes link for beta 19 release notes

- docs/api-reference/stages.rst
- pulpcore/plugin/stages/__init__.py
- pulpcore/plugin/stages/artifact_stages.py
- pulpcore/plugin/stages/content_stages.py
- pulpcore/plugin/stages/declarative_version.py
https://pulp.plan.io/issues/4246
> Add separate remote artifact stage.

- docs/release-notes/index.rst
> Fixing typo in the release note link

- pulpcore/plugin/stages/declarative_version.py
> Remove second occurance of ResolveContentFutures

- pulpcore/plugin/stages/artifact_stages.py
Using prefetching, the stage can be implemented using 2 DB queries per
batch. The WHERE clauses use pks only. For example:
```
[{'sql': 'SELECT "pulp_app_contentartifact"."_id", '
'"pulp_app_contentartifact"."_created", '
'"pulp_app_contentartifact"."_last_updated", '
'"pulp_app_contentartifact"."artifact_id", '
'"pulp_app_contentartifact"."content_id", '
'"pulp_app_contentartifact"."relative_path" FROM '
'"pulp_app_contentartifact" WHERE '
'"pulp_app_contentartifact"."content_id" IN (1, 2, 3, 4, 5, 6, 7, 8, '
'9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, '
'26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, '
'43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, '
'60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, ' …
```
> Improve RemoteArtifactSaver stage

- pull_request_template.md
> Shorten the PR template

- pulpcore/plugin/serializers.py
Required PR: https://github.com/pulp/pulp/pull/3858
Required PR: https://github.com/pulp/pulp_file/pull/166
re #4349
https://pulp.plan.io/issues/4394
> Export relative_path_validator

- pulpcore/plugin/serializers.py
Merged prematurely, it depends RequiredPR:
[pulp/pulp#3858](https://github.com/pulp/pulp/pull/3858)
[noissue]
> Revert github.com/pulp/pulpcore-plugin/pull/58

- pulpcore/plugin/serializers.py
Required PR: https://github.com/pulp/pulp/pull/3858
Required PR: https://github.com/pulp/pulp_file/pull/166
re #4349
https://pulp.plan.io/issues/4394
> Export relative_path_validator and SingleContentArtifactField

- .travis/before_script.sh
closes #4187
https://pulp.plan.io/issues/4187
> Use hyphens for Pulp3' system units name.

- docs/plugin-writer/concepts/subclassing/viewsets.rst
- pulpcore/plugin/stages/declarative_version.py
closes #4449
https://pulp.plan.io/issues/4449
> Sync in additive mode by default

- .travis/install.sh
Fixes Travis to checkout and install pulpcore as needed with the repo
move.
https://pulp.plan.io/issues/4444
re #4444
> Updates for pulpcore repo move

- pulpcore/plugin/stages/artifact_stages.py
- pulpcore/plugin/stages/content_stages.py
- pulpcore/tests/unit/stages/test_artifactdownloader.py
re: #4270
https://pulp.plan.io/issues/4270
> Make changes to support UUID Primary Keys

- .travis/install.sh
> Install pulpcore with postgres extras

- pulpcore/plugin/stages/content_stages.py
fixes #4522
https://pulp.plan.io/issues/4522
> Fix issue with lazy sync where artifacts are None

- docs/release-notes/index.rst
- setup.py
> Adds release notes for beta 21

- pulpcore/plugin/stages/association_stages.py
closes #4505
https://pulp.plan.io/issues/4505
> Fix serious performance issue w/ large syncs

- docs/release-notes/index.rst
- setup.py
> Preparing for 0.1.0rc1

- docs/api-reference/stages.rst
- docs/plugin-writer/concepts/index.rst
- docs/plugin-writer/concepts/sync_pipeline/sync_pipeline.rst
- docs/plugin-writer/concepts/tasks/add-remove.rst
- docs/reference/lazy-support.rst
https://pulp.plan.io/issues/4406
re #4406
> Document stages concept

- docs/plugin-writer/concepts/sync_pipeline/sync_pipeline.rst
- docs/reference/lazy-support.rst
https://pulp.plan.io/issues/4406
clses #4406
> Small syntax/spelling docs fix

- docs/plugin-writer/concepts/subclassing/models.rst
Adds a section in the modeling area describing the problem.
https://pulp.plan.io/issues/4653
closes #4653
> Adding ForeignKey database gotcha

- .travis/before_script.sh
- .travis/pulp-smash-config.json
https://pulp.plan.io/issues/4556
Content: 8080 -> 24816
API: 8000 -> 24817
[noissue]
Required PR: https://github.com/pulp/pulpcore/pull/75
> Change Pulp 3 Default Ports

- pulpcore/plugin/serializers.py
- pulpcore/plugin/viewsets.py
ref #4678
https://pulp.plan.io/issues/4678
> Expose publication models

- pulpcore/plugin/serializers.py
Add a method for erroring on unknown args to the API, since it's useful
for plugin endpoints.
[noissue]
> Add helper method to API

- pulpcore/plugin/download/factory.py
Solutions: use cadata object to pass in a chain of certs
This patch enables the download factory to construct downloaders from certificates stored in the db.
The cadata object is constructed based on documentation[0].
[0] https://docs.python.org/3.5/library/ssl.html#ssl-certificates
re: #4506
https://pulp.plan.io/issues/4506
> Problem: downloader factory requires ssl certs as files

- pulpcore/plugin/serializers.py
> Remove RepositoryPublishURLSerializer

- pulpcore/plugin/serializers.py
- pulpcore/plugin/viewsets.py
Required PR: https://github.com/pulp/pulpcore/pull/117
Ref #4785
> Add classes necessary for subclassing master/detail distributions

- docs/plugin-writer/custom-installation-tasks.rst
- docs/plugin-writer/index.rst
Document how to add custom installation task to
ansible-pulp installer.
closes: #4494
https://pulp.plan.io/issues/4494
Signed-off-by: Pavel Picka <ppicka@redhat.com>
> Custom installation tasks doc

- pulpcore/plugin/__init__.py
- setup.py
> Bumps verison to 0.1.0rc3.dev

- pulpcore/plugin/download/factory.py
Solution: flush ssl related files to disk before using
fixes: #4825
https://pulp.plan.io/issues/4825
> Problem: can't sync from ssl protected repos

- CHANGES.rst
- CHANGES/4875.doc
- CHANGES/4990.doc
- CHANGES/4990.removal
- CHANGES/5011.bugfix
- pulpcore/plugin/__init__.py
- setup.py
> Set 0.1.0rc3 version and generate changelog

- pulpcore/plugin/__init__.py
- setup.py
> Bump version to 0.1.0rc4.dev

- CHANGES/5103.feature
- pulpcore/plugin/viewsets.py
closes #5103
https://pulp.plan.io/issues/5103
> Add HyperlinkRelatedFilter to plugin API

- CHANGES.rst
- CHANGES/3972.doc
- CHANGES/5077.feature
- CHANGES/5103.feature
- CHANGES/5166.doc
- pulpcore/plugin/__init__.py
- setup.py
> 0.1.0rc4 Release

- pulpcore/plugin/__init__.py
- setup.py
> Version bump to 0.1.0rc5.dev

- pulpcore/plugin/viewsets.py
closes #5182
https://pulp.plan.io/issues/5182
> As a user I can filter char fields by multiple values

- CHANGES/5182.feature
https://pulp.plan.io/issues/5182
ref #5182
> Add release note for CharInFilter

- CHANGES.rst
- CHANGES/4681.bugfix
- CHANGES/4681.doc
- CHANGES/5182.feature
- CHANGES/5290.doc
- CHANGES/5290.feature
- CHANGES/5323.bugfix
- pulpcore/plugin/__init__.py
- setup.py
> RC5 release

- pulpcore/plugin/__init__.py
- setup.py
> Bumping release for rc6

- docs/plugin-writer/concepts/sync_pipeline/sync_pipeline.rst
remove second occurrence of ArtifacSaver from list in docs.
closes #5392
https://pulp.plan.io/issues/5392
> ArtifactSaver stage mentioned twice

- CHANGES/5421.feature
ref #5421
https://pulp.plan.io/issues/5421
> Added plugin_managed field on repository

- CHANGES/5403.feature
- docs/plugin-writer/concepts/subclassing/viewsets.rst
- pulpcore/plugin/serializers/__init__.py
- pulpcore/plugin/serializers/content.py
- pulpcore/plugin/viewsets/__init__.py
- pulpcore/plugin/viewsets/content.py
fixes #5403
https://pulp.plan.io/issues/5403
> Add SingleArtifactContentUploadSerializer

- CHANGES/5129.doc
- CHANGES/5129.removal
- docs/plugin-writer/concepts/subclassing/models.rst
refs #5129
https://pulp.plan.io/issues/5129
> Removing mariadb support

- CHANGES.rst
- CHANGES/5129.doc
- CHANGES/5129.removal
- CHANGES/5184.feature
- CHANGES/5304.feature
- CHANGES/5304.removal
- CHANGES/5403.feature
- CHANGES/5413.feature
- CHANGES/5421.feature
- CHANGES/5444.misc
- CHANGES/5444.removal
- CHANGES/5465.removal
- pulpcore/plugin/__init__.py
- setup.py
> 0.1.0rc6 release

- pulpcore/plugin/__init__.py
- setup.py
> 0.1.0rc7.dev

- CHANGES/5442.removal
- docs/api-reference/download.rst
- docs/reference/error-handling.rst
- pulpcore/plugin/models/__init__.py
- pulpcore/plugin/tasking.py
fixes #5442
https://pulp.plan.io/issues/5442
> Remove Task facade

- CHANGES/5537.removal
- docs/api-reference/download.rst
- docs/reference/error-handling.rst
ref #5537
https://pulp.plan.io/issues/5537
Related to https://github.com/pulp/pulpcore/pull/328
> Removing non_fatal_errors from Task model

- CHANGES/5457.removal
- pulpcore/plugin/stages/artifact_stages.py
- pulpcore/plugin/stages/content_stages.py
- pulpcore/plugin/viewsets/content.py
closes #5457
https://pulp.plan.io/issues/5457
> renaming fields

- CHANGES/5543.bugfix
- pulpcore/plugin/serializers/content.py
Fix fields filter for SingleArtifactContentUploadSerializer
closes #5543
https://pulp.plan.io/issues/5543
> Fix fields filter

- CHANGES.rst
- CHANGES/5008.feature
- CHANGES/5442.removal
- CHANGES/5457.removal
- CHANGES/5535.feature
- CHANGES/5537.removal
- CHANGES/5543.bugfix
- CHANGES/5562.doc
- pulpcore/plugin/__init__.py
- setup.py
Now depends on pulpcore>=3.0.0rc7 also.
[noissue]
Required PR: https://github.com/pulp/pulpcore/pull/338
> Version Bump 0.1.0rc7
