pulp/pulpcore-plugin

pulpcore/plugin/stages/__init__.py, pulpcore/plugin/stages/association_stages.py, pulpcore/plugin/stages/declarative_version.py
Some plugins have uniqueness constraints for what content may be in the
same repository version. This new stage enables the DeclarativeVersion
to remove content to make room for incoming content.
https://pulp.plan.io/issues/3934
fixes #3934
=> Allow repoversion-content uniquness constraints

pulpcore/plugin/content.py
Plugin writers need to be able to subclass-to-customize the Handler we
use. They also need to access the app instance users will configure to
run so plugin URLs can be served.
https://pulp.plan.io/issues/4273
closes #4273
=> Add the Handler and aiohttp.web.Application to API

pulpcore/plugin/download/factory.py, pulpcore/plugin/stages/artifact_stages.py
Rename the 'connection_limit' to 'download_concurrency'
throughout the codebase and comments in the codebase to
variable name to be more understandable.
closes: #4114
https://pulp.plan.io/issues/4114
Signed-off-by: Pavel Picka <ppicka@redhat.com>
=> Rename connection_limit to download_concurrency

pulpcore/plugin/content.py
Derived content handlers may want to use the exception (e.g in live APIs).
ref #4273
https://pulp.plan.io/issues/4273
=> Add PathNotResolved exception from content app to plugin API

docs/reference/index.rst, docs/reference/lazy-support.rst
This adds a new section to the reference guide called "Lazy Support".
https://pulp.plan.io/issues/3695
closes #3695
=> Add docs on lazy support for plugins

docs/api-reference/stages.rst
=> The get_future() method is missing in the docs

pulpcore/plugin/stages/api.py, pulpcore/plugin/stages/models.py
Adds missing docstring on `_connect()`.
Although, the log statements really helped with troubleshooting the docker plugin I'm not convinced that they are a worth-while addition.  Thoughts?
Preventing `Stage.put()` of `None` will prevent plugin writers from accidentally doing it.  I burned a good bit of time troubleshooting this because it just causes the pipeline to stall.  Same for the duplicate stage check in `create_pipeline()`.
=> Troubleshooting support; docstrings. [noissue]

docs/release-notes/index.rst, setup.py
Beta 18 was broken because it depended on pulpcore beta 19. Beta 20 is needed.
[noissue]
=> Version bump for beta 19

pulpcore/plugin/stages/api.py, pulpcore/plugin/stages/content_stages.py, pulpcore/plugin/stages/models.py, pulpcore/tests/unit/stages/test_stages.py
DeclarativeContent with an attached future are meant to result in more
DeclarativeContent from the first stage. Therefore blocking them while
waiting for batches to fill, can result in deadlocks.
closes: #4296
https://pulp.plan.io/issues/4296
=> Prevent content with future to deadlock

docs/release-notes/index.rst, setup.py
Beta 20.
Refit to use tags in release notes.
=> bump to: 0.1.0b20. [noissue].

docs/api-reference/stages.rst
Fix builder failure caused by #45 and adds missing `pipeline_stages()` method used by plugin writers.
=> get_future() removed; pipeline_stages() added. [noissue].

docs/api-reference/stages.rst, docs/plugin-writer/concepts/subclassing/serializers.rst, docs/plugin-writer/concepts/tasks/add-remove.rst, pulpcore/plugin/stages/api.py, pulpcore/plugin/stages/association_stages.py, pulpcore/plugin/stages/declarative_version.py
=> Improve, cleanup API-docs

.travis.yml, .travis/install.sh
Note that I am not creating a separate job for testing the docs. We're
limited by the number of concurrent jobs in the Pulp org so I figure
it's more efficient to execute the docs check during the normal test
since it only adds 30-60 seconds.
fixes #4403
https://pulp.plan.io/issues/4403
=> Test building docs against PRs

docs/plugin-writer/concepts/subclassing/models.rst
File content is always 1 file.
Fixed in plugin-writer doc.
closes: #4372
https://pulp.plan.io/issues/4372
Required PR: https://github.com/pulp/pulp_file/pull/173
Signed-off-by: Pavel Picka <ppicka@redhat.com>
=> Fix FileContent description in docs

docs/reference/lazy-support.rst, pulpcore/plugin/stages/artifact_stages.py, pulpcore/plugin/stages/declarative_version.py, pulpcore/plugin/stages/models.py
Required PR: pulp/pulp_file#177
https://pulp.plan.io/issues/4209
re #4209
=> Add always_download to DeclarativeArtifact

pulpcore/plugin/serializers.py
Solution: Add BaseDistributionSerializer to the plugin API
re: #4435
https://pulp.plan.io/issues/4435
re: #4437
https://pulp.plan.io/issues/4437
=> Problem: BaserDistributionSerializer not available in plugin API

pulpcore/plugin/models/content.py, pulpcore/plugin/models/remote.py
Solution: add interfaces that enable pass-through cache for plugins
This patch extends the Remote API. It adds an interface for determining the full URL of a RemoteArtifact
by examining the relative path and the Remote's url. It also adds an interface for determining the type of
content that should be available at a relative path of a remote. These interfaces are used by the content
app when serving content in the pass-through cache mode. The content app needs to determine what URL is
actually being requested and what kind of content is being requested by the client.
This patch also extends the Content API. It adds a new constructor method to the Content model. This new
interface is a constructor that take an Artifact and a relative path to produce an unsaved instance of a
specific …
=> Problem: plugin API missing pass-through cache interfaces

.travis/before_script.sh, .travis/script.sh, docs/api-reference/profiling.rst, docs/plugin-writer/concepts/subclassing/models.rst
Solution: use django-admin directly
re: #4450
https://pulp.plan.io/issues/4450
=> Problem: pulp-manager is not needed

pulpcore/tests/unit/models/test_content.py, pulpcore/tests/unit/models/test_repo_ver.py
Adding unit tests for content and repository version models.
re: #4348
https://pulp.plan.io/issues/4348
Signed-off-by: Pavel Picka <ppicka@redhat.com>
=> Few unittests for plugin-api

.travis/install.sh
It was being installed using the github URL instead of filesystem, not
being able to run some tests due to the location of them -
site-packages.
=> Fix installation process for pulp_file

doc_requirements.txt
The tests don't need psycopg2.
https://pulp.plan.io/issues/4639
closes #4639
=> Remove test dependency on psycopg2

docs/reference/how-to-doc-api.rst
Solution: add more docs in the 'Documenting your API' section
[noissue]
=> Problem: docs missing for how to generate OpenAPI schema

pulpcore/plugin/stages/content_stages.py
Do as the current documentation states (`This stage inspects any "unsaved"
Content unit objects and searches for existing saved Content units inside
Pulp with the same unit key`) and do not query for content that is already saved.
https://pulp.plan.io/issues/4746
closes #4746
=> Do not query saved content in QueryExistingContents stage

docs/release-notes/index.rst, setup.py
This adds a release notes section which includes the up-to-date breaking
changes. It also version bumps this pacakge to 0.1.0rc2 and will depend
on pulpcore 3.0.0rc2.
[noissue]
=> Add release notes and version bump to rc2

docs/api-reference/content-app.rst, docs/api-reference/index.rst
This adds a new section of documentation on making customized Content
app URLs.
Required PR: https://github.com/pulp/pulpcore/pull/137
https://pulp.plan.io/issues/4719
closes #4719
=> Adds Handler docs to plugin docs

.travis.yml, .travis/docs-builder.py
Solution: include the docs publishing stage for all tagged builds
closes #4821
https://pulp.plan.io/issues/4821
=> Problem: docs not publishing for tagged builds

pulpcore/plugin/serializers.py
refs #4827
https://pulp.plan.io/issues/4827
=> Expose ContentChecksumSerializer

CHANGES.rst, CHANGES/.TEMPLATE.rst, CHANGES/.gitignore, CHANGES/4875.doc, HISTORY.rst, doc_requirements.txt, docs/changes.rst, docs/contributing.rst, docs/index.rst, docs/reference/releasing.rst, pulpcore/plugin/__init__.py, pyproject.toml
- Adds a changelog update section to the docs
- creates the base CHANGES.rst file
- creates the CHANGES directory for news updates and indicates to git to
store the dir even if empty with a .gitignore.
- adds a release note for this change
- adds a docs section that loads the CHANGES.rst file on the website
https://pulp.plan.io/issues/4875
re #4875
=> Add new changelog process

CHANGES/5011.bugfix, pulpcore/plugin/download/http.py
Solution: pass in the proxy url to the get() request
fixes: #5011
https://pulp.plan.io/issues/5011
=> Problem: remote's proxy_url setting not being used during sync

CHANGES/4990.doc, CHANGES/4990.removal, docs/plugin-writer/concepts/sync_pipeline/sync_pipeline.rst, docs/reference/index.rst, docs/reference/on-demand-support.rst, pulpcore/plugin/stages/content_stages.py, pulpcore/plugin/stages/models.py
This replaces the language of 'lazy' with 'on-demand' also.
https://pulp.plan.io/issues/4990
closes #4990
=> Add notes about on-demand in changelog

CHANGES/5077.feature, pulpcore/plugin/exceptions.py
The `DigestValidationError` and `SizeValidationError` validation
exceptions were not available in the plugin API. Now they are available
in `pulpcore.plugin.exceptions` package.
https://pulp.plan.io/issues/5077
closes #5077
=> Add validation exceptions to plugin API

CHANGES/3972.doc, docs/plugin-writer/concepts/index.rst, docs/reference/content-protection.rst, docs/reference/index.rst
The ``ContentGuard`` was usable in the plugin API before, but there were
not very good docs on it. This explains to plugin writers how to define
and use detail ``ContentGuard`` objects.
https://pulp.plan.io/issues/3972
closes #3972
=> Adds ``ContentGuard`` plugin writer docs

CHANGES/4681.bugfix, CHANGES/4681.doc, docs/plugin-writer/concepts/subclassing/models.rst
ref #4681
related to: https://github.com/pulp/pulpcore/pull/259
=> Updating docs for subclassing models

CHANGES/5290.doc, CHANGES/5290.feature, docs/plugin-writer/concepts/index.rst
Plugin writers can add settings programatically using the docs provided
with this commit.
https://pulp.plan.io/issues/5290
closes #5290
=> Add docs on programatic plugin settings

.gitignore, CHANGES/5184.feature, pulpcore/plugin/stages/artifact_stages.py, pulpcore/plugin/stages/association_stages.py
ref #5184
https://pulp.plan.io/issues/5184
Required PR: https://github.com/pulp/pulpcore/pull/289
Required PR: https://github.com/pulp/pulp_file/pull/272
=> adding code on progress bar

CHANGES/5413.feature, pulpcore/plugin/stages/artifact_stages.py, pulpcore/plugin/stages/models.py, pulpcore/tests/unit/stages/test_artifactdownloader.py
This patch introduces an additional check to the method that schedules Artifact
downloading. DeclarativeArtifacts that contain an Artifact that already has a file
are not scheduled for download.
This patch also makes the remote required for the DeclarativeArtifact unless the Artifact
already has a file associated with it.
closes: #5413
https://pulp.plan.io/issues/5413
re: #5172
https://pulp.plan.io/issues/5172
=> Skip downloading DeclarativeArtifacts if a file is already present

CHANGES/5465.removal, pulpcore/plugin/fields.py
We're using Django's from now on, not our own.
re: 5465
https://pulp.plan.io/issues/5465
=> Remove JSONField from public API

CHANGES/5304.feature, CHANGES/5304.removal, docs/plugin-writer/concepts/tasks/publish.rst, docs/reference/object-relationships.rst
re: #5304
https://pulp.plan.io/issues/5304
=> Add change log entries for PublishedMetadata change

CHANGES/5535.feature, docs/plugin-writer/concepts/subclassing/viewsets.rst, docs/plugin-writer/plugin-walkthrough.rst, pulpcore/plugin/viewsets/__init__.py
re #5535
https://pulp.plan.io/issues/5535
Required PR: https://github.com/pulp/pulpcore/pull/322
=> Add ReadOnlyContentViewset

CHANGES/5008.feature
The feature is actually in pulpcore's code, but the release note needs
to be in this package, which imports it.
Related PR:  https://github.com/pulp/pulpcore/pull/331
https://pulp.plan.io/issues/5008
closes #5008
=> Add release note for changes in pulpcore

CHANGES/5562.doc, docs/reference/how-to-doc-api.rst
closes #5562
https://pulp.plan.io/issues/5562
=> Document explicit definition of ref_name on the serializer.
